"""
Django settings for Backend project.

Generated by 'django-admin startproject' using Django 6.0.2.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""
import os
import dj_database_url
from pathlib import Path
from decouple import config
from datetime import timedelta

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = config('SECRET_KEY')

DEBUG = False  # <-- CAMBIAR A False EN PRODUCCIÓN

# validar host y dominios permitidos
ALLOWED_HOSTS = ['localhost', '127.0.0.1', '0.0.0.0', '.onrender.com', '.railway.app','192.168.0.18','.vercel.app']  

# Configuración de CSRF para producción
CSRF_TRUSTED_ORIGINS = [
    'https://*.railway.app',
    config('FRONTEND_URL'),
]

# Application definition
INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.sites',

    #thir party
    'rest_framework',
    'corsheaders',
    'allauth',  
    'allauth.account',  
    'allauth.socialaccount',  
    'allauth.socialaccount.providers.google',
    'google.oauth2',

    #local apps
    'usuarios',
]

ROOT_URLCONF = 'Backend.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'Backend.wsgi.application'

# --- CONFIGURACIÓN PARA DESARROLLO LOCAL ---
# DATABASES = {
#     'default': {
#         'ENGINE': 'django.db.backends.postgresql',
#         'NAME': config('DB_NAME'),
#         'USER': config('DB_USER'),
#         'PASSWORD': config('DB_PASSWORD'),
#         'HOST': config('DB_HOST'),
#         'PORT': config('DB_PORT'),
#     }
# }

# --- CONFIGURACIÓN PARA PRODUCCIÓN ---
# Descomenta este bloque y comenta el de arriba cuando subas a producción
DATABASES = {
    'default': dj_database_url.config(
        default=config('DATABASE_URL'),
        conn_max_age=600,
        ssl_require=True  # Importante para Render
    )
}


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = 'static/'


STATIC_ROOT = BASE_DIR / 'staticfiles'  # <-- DESCOMENTAR EN PRODUCCIÓN


# Default authentication JWT classes for Django REST Framework
# https://www.django-rest-framework.org/api-guide/authentication/#setting-the-authentication-scheme
REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'rest_framework_simplejwt.authentication.JWTAuthentication',
    ),
}

SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME': timedelta(minutes=30),
    'REFRESH_TOKEN_LIFETIME': timedelta(days=1),
    'AUTH_HEADER_TYPES': ('Bearer',),
}

AUTH_USER_MODEL = 'usuarios.Usuario'

#middleware para CORS
MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',  # 👈 DEBE SER EL PRIMERO
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',  # <-- DESCOMENTAR EN PRODUCCIÓN
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'allauth.account.middleware.AccountMiddleware',  # 👈 NUEVO
]

#permisos para el frontend
CORS_ALLOWED_ORIGINS = [
    "http://localhost",
    "http://127.0.0.1",
    "http://localhost:5173",
    "http://127.0.0.1:5173",
    config('FRONTEND_URL'),
]


# Configuración adicional de CORS
CORS_ALLOW_CREDENTIALS = True
CORS_ALLOW_HEADERS = [
    'accept',
    'accept-encoding',
    'authorization',
    'content-type',
    'dnt',
    'origin',
    'user-agent',
    'x-csrftoken',
    'x-requested-with',
]


# --- CONFIGURACIÓN LOCAL (para pruebas) ---
# EMAIL_BACKEND = 'django.core.mail.backends.console.EmailBackend'
# DEFAULT_FROM_EMAIL = 'noreply@tuaplicacion.com'

# --- CONFIGURACIÓN PRODUCCIÓN (envía emails reales) ---
EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = 'smtp.gmail.com'
EMAIL_PORT = 587
EMAIL_USE_TLS = True
EMAIL_HOST_USER = config('EMAIL_HOST_USER') 
EMAIL_HOST_PASSWORD = config('EMAIL_HOST_PASSWORD')  
DEFAULT_FROM_EMAIL = config('EMAIL_HOST_USER')

#timeout para el envío de emails
EMAIL_TIMEOUT = 10  # segundos

# Usar conexión persistente (ahorra recursos)
EMAIL_USE_LOCALTIME = True

#site id para django-allauth
SITE_ID = 1

#configuración de allauth
AUTHENTICATION_BACKENDS = [
    'django.contrib.auth.backends.ModelBackend',
    'allauth.account.auth_backends.AuthenticationBackend',
]

#Configuración de allauth
ACCOUNT_EMAIL_REQUIRED = True
ACCOUNT_USERNAME_REQUIRED = True
ACCOUNT_AUTHENTICATION_METHOD = 'username_email'
ACCOUNT_EMAIL_VERIFICATION = 'mandatory'  # <-- CAMBIAR A 'mandatory' EN PRODUCCIÓN y 'none' para local 

# Configuración de Google OAuth
SOCIALACCOUNT_PROVIDERS = {
    'google': {
        'SCOPE': [
            'profile',
            'email',
        ],
        'AUTH_PARAMS': {
            'access_type': 'online',
        },
        'APP': {
            'client_id': config('GOOGLE_CLIENT_ID'),
            'secret': config('GOOGLE_CLIENT_SECRET'),
            'key': ''
        }
    }
}

# --- LOCAL ---
# LOGIN_REDIRECT_URL = 'http://localhost:5173/cliente'
# ACCOUNT_LOGOUT_REDIRECT_URL = 'http://localhost:5173/login'

# --- PRODUCCIÓN ---
# Descomenta esto y comenta las URLs de localhost arriba
FRONTEND_URL = config('FRONTEND_URL')
LOGIN_REDIRECT_URL = f'{FRONTEND_URL}/cliente'
ACCOUNT_LOGOUT_REDIRECT_URL = f'{FRONTEND_URL}/login'


# =====================================================
# LISTA DE VERIFICACIÓN PARA PRODUCCIÓN
# ===================================================== 
# 1. DEBUG = False
# 2. ALLOWED_HOSTS con tus dominios
# 3. Comentar DATABASES local y descomentar DATABASES producción
# 4. Descomentar STATIC_ROOT y whitenoise
# 5. Agregar dominios de producción en CORS_ALLOWED_ORIGINS
# 6. Cambiar EMAIL_BACKEND a SMTP real
# 7. ACCOUNT_EMAIL_VERIFICATION = 'mandatory'
# 8. Cambiar LOGIN_REDIRECT_URL a FRONTEND_URL
# 9. Verificar que todas las variables de entorno están en producción
# 10. Ejecutar: python manage.py collectstatic
# 11. Ejecutar: python manage.py migrate
