# Generated by Django 6.0.2 on 2026-02-24 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0002_alter_permiso_options_alter_usuario_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='permiso',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
